#!/usr/bin/env tsx
/**
 * Regenerate `.claude/skills/<id>/SKILL.md` for every product skill from its
 * YAML definition. The SKILL.md is a thin generated wrapper — the definition is
 * the source of truth. CI checks that running this leaves no diff.
 *
 *   pnpm --filter @agentic-sales-hub/skills exec tsx src/scripts/sync-claude-skills.ts [--check]
 */
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { listSkills } from "../registry.js";
import { PRODUCT_SKILL_IDS } from "../types.js";
import type { SkillDefinition } from "@agentic-sales-hub/context-core";

function repoRoot(): string {
  let dir = dirname(fileURLToPath(import.meta.url));
  for (let i = 0; i < 8; i++) {
    if (existsSync(join(dir, "pnpm-workspace.yaml"))) return dir;
    dir = dirname(dir);
  }
  throw new Error("could not locate repo root");
}

function toolToAllowed(tool: string): string {
  // context.read / context.search / artifact.write -> a stable allowed-tools token
  return tool;
}

function renderSkillMd(def: SkillDefinition): string {
  const allowed = def.tools.map(toolToAllowed).join(", ");
  const grantLines = def.context_grants.read.map((g) => `  - \`${g}\``).join("\n");
  return `---
name: ${def.id}
description: ${def.description ?? `${def.id} (${def.tier} skill)`}
allowed-tools: ${allowed}
---

# ${def.id}

> **Generated from \`packages/skills/src/definitions/${def.id}.yaml\`.**
> Do not edit this file by hand. Run \`pnpm skills:sync\` after changing the
> definition; CI fails on drift.

**Tier:** ${def.tier} · **Version:** ${def.version}

${def.description ?? ""}

## How to run it

Invoke \`runSkill('${def.id}', input, ctx)\` from \`@agentic-sales-hub/skills\`. Do not
re-implement the logic inline — the one definition drives this skill, the MCP
tool, and the eval runner.

## Inputs

${Object.entries(def.inputs)
  .map(
    ([name, spec]) => `- \`${name}\` (${spec.type}${spec.required ? ", required" : ", optional"})`,
  )
  .join("\n")}

## Context read scope

${grantLines}
${def.tier === "review" ? "\n_No write grant. Review skills return findings; a separate step persists them._\n" : ""}
## Output contract

\`${def.output.schema}\`${def.output.requires_citations ? " — every material claim carries a resolvable citation." : ""}

## Evaluated by

\`${def.eval_suite}\`
`;
}

async function main(): Promise<void> {
  const check = process.argv.includes("--check");
  const root = repoRoot();
  const skills = (await listSkills()).filter((s) =>
    (PRODUCT_SKILL_IDS as readonly string[]).includes(s.id),
  );

  let drift = false;
  for (const def of skills) {
    const path = join(root, ".claude/skills", def.id, "SKILL.md");
    const next = renderSkillMd(def);
    const current = existsSync(path) ? await readFile(path, "utf8") : null;
    if (current === next) continue;

    if (check) {
      drift = true;
      console.error(`drift: ${def.id}/SKILL.md is out of sync with its definition`);
    } else {
      await mkdir(dirname(path), { recursive: true });
      await writeFile(path, next, "utf8");
      console.log(`wrote .claude/skills/${def.id}/SKILL.md`);
    }
  }

  if (check && drift) process.exit(1);
  if (check) console.log("sync-claude-skills: no drift");
}

await main();
